// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHDMNA9KYp5m7nTGcYW559MJCOf0Iz6M',
    appId: '1:2569474194:web:acc840e80b67220509564b',
    messagingSenderId: '2569474194',
    projectId: 'my-flutter-project-id',
    authDomain: 'my-flutter-project-id.firebaseapp.com',
    storageBucket: 'my-flutter-project-id.firebasestorage.app',
    measurementId: 'G-4KNTF9BZFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2B7HVJU7w3twvcGexUD0gIYzKl0c4cso',
    appId: '1:2569474194:android:670b865c5ac4fa9309564b',
    messagingSenderId: '2569474194',
    projectId: 'my-flutter-project-id',
    storageBucket: 'my-flutter-project-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXmt-7fT4LcLmzsmcRJE_oWYLR27IDN7I',
    appId: '1:2569474194:ios:3c09f75c62a8662009564b',
    messagingSenderId: '2569474194',
    projectId: 'my-flutter-project-id',
    storageBucket: 'my-flutter-project-id.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotifDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXmt-7fT4LcLmzsmcRJE_oWYLR27IDN7I',
    appId: '1:2569474194:ios:3c09f75c62a8662009564b',
    messagingSenderId: '2569474194',
    projectId: 'my-flutter-project-id',
    storageBucket: 'my-flutter-project-id.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotifDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcHDMNA9KYp5m7nTGcYW559MJCOf0Iz6M',
    appId: '1:2569474194:web:72016041d66c90be09564b',
    messagingSenderId: '2569474194',
    projectId: 'my-flutter-project-id',
    authDomain: 'my-flutter-project-id.firebaseapp.com',
    storageBucket: 'my-flutter-project-id.firebasestorage.app',
    measurementId: 'G-RZ732XKPLX',
  );
}
